version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.3.3
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build 
          command: |
            if [ "${CIRCLE_BRANCH}" == "ubuntu" ]; then
              packer build build_ubuntu.json
            fi
            if [ "${CIRCLE_BRANCH}" == "amazon" ]; then
              packer build build_amazon.json
            fi
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: AMI
